# Generated by Django 3.0.7 on 2020-06-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tmdb_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
